spring.application.name=admin-service

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# JWT
jwt.secret=bookstore_super_secret_key_2024_very_long_string
jwt.expiry=86400000

# Swagger / OpenAPI
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.packages-to-scan=com.bookstore.admin

springdoc.override-with-generic-response=false
springdoc.default-produces-media-type=application/json

# Debug (helps if error persists)
springdoc.writer-with-default-pretty-printer=true

# Spring
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=update