server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5437/admin_db
spring.datasource.username=admin
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false