server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5439/user_db
spring.datasource.username=admin
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=bookstore_super_secret_key_2024_very_long_string
jwt.expiry=86400000

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs