spring.application.name=cart-service
spring.config.import=optional:configserver:http://localhost:8888
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
jwt.secret=bookstore_super_secret_key_2024_very_long_string
jwt.expiry=86400000