spring.application.name=config-server
server.port=8888

# Use classpath (local) configs instead of Git
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/configs

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true